version: '3.8'
services:
  server:
    build: .
    tty: true
    volumes:
      - ./server:/app
      - ./m2:/root/.m2
    ports:
      - "8686:8686"

  client:
    build: .
    tty: true
    volumes:
      - ./client:/app
      - ./m2:/root/.m2
    links:
      - server
